name: Commit artifact
on:
  workflow_call:
    inputs:
      artifact_name:
        description: "Name of artifact to download"
        required: true
        type: string
        default: artifact
      artifact_folder:
        description: "Folder name to store artifacts"
        required: true
        type: string
        default: folder

jobs:
  commit:
    name: Commit artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout self
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2

    - name: Download ${{ inputs.artifact_name }}
      uses: actions/download-artifact@v4
      with: 
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_folder }}

    - name: Get last commit message
      run: echo "commit_msg=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

    - name: Commit self
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: ${{ env.commit_msg }}
        commit_options: '--amend --no-edit'
        push_options: '--force'
        skip_fetch: true
